issue# 669 and issue# 668
opensrp/opensrp-client-anc pull request #692
Opened 2021-10-27 11:41 UTC by junaidwarsivd

Anc issue  https://github.com/opensrp/opensrp-client-anc/issues/669
Anc issue  https://github.com/opensrp/opensrp-client-anc/issues/668

2021-11-08 11:59 UTC, ellykits requested changes

2021-11-08 11:59 UTC, ellykits commented on opensrp-anc/src/main/java/org/smartregister/anc/library/util/Utils.java
> +            if((key.equals("nausea_pharma") || key.equals("antacid") || key.equals("penicillin") || key.equals("antibiotic") || key.equals("ifa_medication")) && (value!= null && value.equals("0")))
Extract the strings to constants

2021-11-08 11:59 UTC, ellykits commented on opensrp-anc/src/main/java/org/smartregister/anc/library/util/Utils.java
> +            if (item.length() > 0 && !item.trim().equals("")) {
I think you can use the utility method `StringUtils#isNotBlank` for this use case. It will take care of the extra white spaces

2021-11-25 15:09 UTC, dubdabasoduba approved these changes

2021-11-25 15:09 UTC, merged