Generate a pdf file for Contact summary screen data
opensrp/opensrp-client-anc pull request #699
Opened 2021-11-04 16:55 UTC by shoaibmushtaq25

Fixes #683

2021-11-08 08:18 UTC, dubdabasoduba requested changes

2021-11-08 08:18 UTC, dubdabasoduba commented on opensrp-anc/src/main/java/org/smartregister/anc/library/activity/ContactSummaryFinishActivity.java
> +                e.printStackTrace();
Update this to use timber

2021-11-08 10:10 UTC, shoaibmushtaq25 commented on opensrp-anc/src/main/java/org/smartregister/anc/library/activity/ContactSummaryFinishActivity.java
> +                e.printStackTrace();
okay, let me

2021-11-08 10:15 UTC, shoaibmushtaq25 commented on opensrp-anc/src/main/java/org/smartregister/anc/library/activity/ContactSummaryFinishActivity.java
> +                e.printStackTrace();
Done

2021-11-25 14:28 UTC, dubdabasoduba approved these changes

2021-11-25 15:08 UTC, merged